# 歸納推理 {#inductive}

> 本單元學習目標：以 @zwaanParticipantNonnaiveteReproducibility2017 重製的九項實驗，學習各種實驗設計搭配的統計方法，如何確認測出關鍵效應。認識心理學研究常見的效果量指標，以及估計方法。延伸學習：如何使用開源統計軟體重製實驗資料分析。

<!---
本單元依預先註冊[@lindsayResearchPreregistration1012016]與註冊報告[@attenperceptpsychophysRegisteredReportsReplications2013]的指南，介紹如何準備研究計畫，以及撰寫研究報告。之前單元提供的再現研究習作，可參考這個單元規劃與執行研究，並完成最後的研究報告。 --->

- 根據九項重製實驗結果的描述統計資訊，如何判斷實驗結果可有效評估研究假設？


- 根據九項實驗的來源文獻(見@tbl-9RP )，如何摘要表現測得實驗效果的統計資訊？


- 摘要 @zwaanParticipantNonnaiveteReproducibility2017 的統計結果，如何說明重製實驗與原始實驗結果一致？


- @zwaanParticipantNonnaiveteReproducibility2017 的研究假設有沒有得到支持？如何從論文裡摘要他們的說法


- @zwaanParticipantNonnaiveteReproducibility2017 指出的研究結果推論限制是什麼？會不會影響一開始的實驗假設？




## 開源統計軟體 {#toolbox_stat}

<!---前一節介紹的三種實驗平台匯出的實驗資料都是長表格，每一列(row)只包含一個觀察值，除了OpenSesame與formr有系統預設欄位資料， psytoolkit的每一欄都是實驗腳本裡有設定的變項。每一份匯出的檔案都是以主要依變項的反應單位排列，只要事先設定的分析計畫要以主要依變項的平均值進行分析，就可以使用試算表的樞紐分析功能計算。

樞紐分析的結果是常用統計分析方法的資料集合，如t檢定、變異數分析。我建議使用JASP與jamovi等開源統計軟體進行分析，使用方式可參考我的網誌[^10]。

[^10]: --->[開源統計軟體介紹](https://scchen.com/zh/post/jasp-jamovi/) 


## 研究倫理基本須知 ## {#projects_ethics}

科學研究能增進人類對這個世界的了解，是每個領域科學家進行研究的主要動機。行為與社會科學的研究對象是人類，運用各種方式取得人類行為資料是研究之必需。儘管研究有崇高的目標，任何取得資料的方式都不能侵害個人利益，或造成任何可能的風險。以下引述 @saulHowWriteLab2011 整理的基本須知，補充最近應該考慮的例子：

- 獲取資料的方式是否會引發參與者心理或生理的不適？ 例如：詢問個人性別不只設計兩個選項，讓跨性別人士自由決定要不要告知。
- 收集資料有無侵犯個人隱私？ 例如在公開場合進行實驗；收集個人手機定位...
- 因實驗操作的需要，事前隱暪部分內容，會不會損害參與者權益？例如：分班實施不同的教學法，比較學生的學習表現。
- 參與者隨時中止參與研究的自由。
- 邀請未成年人士參與研究，應考慮的問題：
- 以非人類動物進行研究，應考慮的問題：
