# 預先註冊研究的寫作指南 {#sec-writing}

> 本單元學習目標：如何參考學術寫作規範撰寫學術報告；如何準備適用公開互動場合的報告材料。延伸學習：如何使用動態文件編輯模組，組織可重製的分析流程。


完成資料分析的寫作報告，實際的樣式要遵守呈現報告的用途指南，如期刊的投稿格式、教師指定的報告樣式。心理學的各種報告樣式，基本上都是遵守美國心理學會頒佈的出版手冊[@AmericanPsychologicalAssociation-2020, 最新版本為第7版，以下簡稱APA 7]，只要保持基本格式及元素能充分呈現研究者的研究輸出及思維脈絡，出版編輯或寫作教學任員都可依照實際需要，調整部分寫作細節。寫作者養成依出版手冊撰寫論文報告的習慣，足以應付任何報告寫作要求。

由於 @sec-intro 曾經提到再現危機，現代心理學研究充斥**發表偏誤**及**不正當的研究操作**，這個單元以德國萊布尼茲心理學院PsychArchives小組推出的量化心理學研究預先註冊模板(Preregistration Standards for Psychology - the Psychological Research Preregistration-Quantitative[^08-wiritng-01]，以下簡稱PRP-QUANT)，以此模板準備報告內的各部分元素，就能構成符合APA 7的報告稿件。

PRP-QUANT不僅僅是一套寫作模板，更是一種實現開放科學理念的行動方案。有開放科學理念的研究者會自發公開分享研究過程中的所有資料和材料，包括原始資料、分析程式碼、實驗材料等。這種方式允許其他研究者驗證研究結果、重製實驗、以及進一步挖掘資料，建立更可靠的科學知識體系。實現開放科學不僅充分符合科學研究誠信原則，也能有效維護科學公信力。

## 學習學術寫作的理由 {#sec-writing_why}

### 為何要撰寫研究報告？

科學研究的最終目的，是為了揭示世界的運作規律、探索自然現象背後的運作機制，並將這些知識應用於解決實際問題。然而，只是做好實驗是不夠的，實驗結果必須以清晰、準確且易於理解的文字及圖表傳達給其他研究者和社會大眾，才能彰顯研究的知識價值。一篇嚴謹清晰的研究報告，不僅能促進學術交流與合作，也能提供其他研究者對研究結果進行驗證和批評，確保科學知識的可靠性和可信度。

科學的進展仰賴知識的累積與傳承，而研究報告是承載研究者努力所收穫的知識載體。透過閱讀和分析過去的研究文獻，研究者可以了解該領域的研究現狀、已知和未知的問題，以及未來的研究方向。研究報告如同鋪路石料，指引著科學家們不斷探索未知的領域，推動人類不斷拓展知識領域的邊界。

###  研究發表文化的挑戰與反思

儘管研究報告寫作在科學研究中扮演著舉足輕重的角色，但心理學領域已發表的報告並非都是無可挑剔。近年來，心理學研究報告的發表文化面臨著一系列的挑戰，這些挑戰不僅威脅心理學研究的信譽，更引發了研究者對於科學研究方法和研究發表體系的反思。

其中，**發表偏差** 已經成為學術出版領域一個難以忽視的問題。由於期刊偏好發表具有統計顯著性和新穎結果的研究，導致許多實驗結果未達統計顯著水準，或者不同於過去文獻的研究被束之高閣。這種選擇性發表的趨勢扭曲了科學文獻的可確信程度，使得專業研究者對於某些現象的理解過於樂觀，並且可能導致研究資源的浪費，以及面對實際問題造成錯誤的決策。

**p 值操縱** 更是放大發表偏差的負面影響。一些研究者過度追求研究結果的統計顯著性，過度操縱資料分析方法、選擇性報告部分研究結果等手段，讓研究結果看起來更具說服力。這種做法不僅違背了科學研究的誠信原則，更可能誤導其他研究者，阻礙科學的進步。




## PRP-QUANT模板格式與元素 {#sec-writing_style}

### 模板設計目的

PRP-QUANT 模板的設計宗旨，是為了改善當前科學研究中常見的弊病，例如發表偏差以及P值操縱等再現危機徵候所揭櫫的問題。使用PRP-QUANT模板的研究者要**在收集資料之前**，就設定好研究計畫，詳細描述研究方法以及資料分析策略，減少研究者事後操縱資料或選擇性報告結果的空間。預先註冊機制不僅有助於提升研究的透明度和可重製性，也讓發表管道的評審者和報告的讀者更容易評估研究結果的可信度。如果心理學研究者都能採用如同 PRP-QUANT 等預先註冊模板準備並執行研究計畫，類似史泰佩爾採用不良手段製造的社會心理學實驗結果，能否被更早揭露，避免或減少善後的成本呢？  

PRP-QUANT 模板有清楚指引，讓研究者運用資源，管理研究過程中應公開呈現的所有資料和研究材料，包括原始資料、分析程式碼、實驗材料等。另一個重要功能是，方便後續的研究結果分析和整合。模板內建議讓研究者如何以標準化資料格式存儲研究資料，讓後續的整合分析研究更容易整合來自不同研究的資料，提高整合分析的效率和準確性，為特定研究議題提供更全面、更可靠的q研究結論。

### 模板結構說明

::: {.callout-note title="演練行動" collapse="true" style="color: yellow"}
運用 @Zwaan-2018 公開的研究前計畫書，分析其中的元素後，置入教學者指定的報告模板檔案。
:::

## 報告寫作指引 {#sec-writing_guide}

以下引用 @saulHowWriteLab2011 的建議，搭配PRP-QUANT 模板的模組化指引，條列一份完整的研究報告各部分寫作建議。

**標題頁**

建議：
- 以口語化問句或肯定句建立標題，描述獨變項操作如何導致依變項的測量結果。
- 預測註冊日期時間、資料可用狀況
- 預先註冊專案文件版本資訊，可運用OSF等網路平台為專案的各項材料生成DOI。

<!---
範例：故事情境會不會讓你覺得故事主角誤會看到的事情？
--->

**摘要**

建議：以百餘字簡介整份研究報告的要點。

 - 開頭句說明研究目標與規劃研究的想法。
 - 簡述研究狀況與參與者條件。
 - 簡述研究方法：獨變項的設定，依變項的測量方式。
 - 簡述主要發現：除了重要統計指標，也可用一句話說明。
 - 字數未達上限，可說明研究結果的重要貢獻。

**緒論**

 - 三建議：以簡明易懂的案例或通俗知識說明研究問題的理論背景；呈現與這次研究最有關係的兩到三項過去發現；建立研究問題、假設到方法的邏輯關聯。
 - 三不可：一網打盡所有過去發現；仔細描述所有相關研究的細節；用雜文筆調寫作。
 - 目標：以過去文獻說明獨變項設定與使用測量方法的理由，預測可能發現的結果。
 - 假設：使用精確用詞描述獨變項與依變項，說明預測成立的原理。完整列出所有要檢則的假設。
 - 探索性問題：非研究假設可預測，分析方法並未完整，但可運用收集的資料探討的問題。

**方法**

 - 說明如何進行實驗的重要細節，讓其他研究者足以根據描述完整再現這次研究為原則。
 - 可適當引用放置公開材料的資料庫網址，提供讀者自行取用。

**設計**

 - 明列獨變項的隨機分派方法、依變項的測量與分數轉換、不做分派的控制變項處置方式、非主要依變項的其他變項如何測量。
 - 交互平衡是最常見的隨機分派方法。
 - 說明估計考驗力的方法。有相同設計的過去研究，可做為估計考驗力的資訊。 

**參與者**

 - 說明參與者加入研究的管道．平均背景資訊與權益保障措施。
 - 說明參與者人數，年齡範圍等，最好有考驗力分析做輔助資訊。

**材料**

 - 介紹使用的字詞、問卷、電腦設備等。不需交待詳細內容與規格，而是展現獨變項操作的差異化條件。
 - 文字或圖像材料可放置於可取用的網路資料庫，提供讀者可獲得材料的連結。

**程序**

 - 說明執行研究的正確過程，足以讓其他研究者重新再現。研究過程使用的指示語、說明、紀錄表等次級文件、可發佈於可取用的網路資料庫。

**結果**

 - 通常先呈現描述統計，再呈現推論統計。這個部分不應詮釋統計結果。
 - 研究者要正確且清晰地報告結果，APA寫作規範有數值與統計符號的建議表達。
 - 採用動態文本(dynamic documents)寫作，讀者能使用公開資料查核報告中的資料與圖表。
 - 如果一句話要呈現的數值超過三個種類，而且總共有十個以上的數字，最好使用表格呈現。

**討論**

 - 使用一般的書面語概述實驗結果，以及指出是否符合假設的預測。
 - 比較與之前研究的同異處。
 - 這項研究結果能擴展的知識界限。
 - 未來可改進的地方。
 - 如果研究結果有可應用性，可表達之。如果有註冊計畫書，應限制在計畫設定的範圍之內。
 - 以三句或四句結尾，通常是摘要的後半部。

**參考文獻**

 - 依指定格式排列引用文獻。
 - 運用可管理與編輯文獻排版格式的書目管理軟體，編輯事半功倍。


## 預寫註冊寫作演練 {#sec-writing_practice}




[^08-wiritng-01]: 讀者可由[模板網頁](https://www.psycharchives.org/en/item/a417b468-7398-40e2-9050-4adad9e2078d)，依照需求下載對應的格式檔案。此網頁的"Related PsychArchives Objects"有相關參考資源。