# 導讀 {.unnumbered}

<!---

Quarto book editing guide
https://quarto.org/docs/books/

--->


### 寫作動機

心理學實驗法是帶領心理學學生了解如何準備及完成一項心理學實驗的課程，也是心理科學研究養成入門。有百年歷史的心理學系都將這門課程設定為必修課，許多有心深入心理學知識殿堂的學生從這門課程找到學涯起點，寫出一本實驗心理學教科書也是一名心理學教師的生涯里程碑。但是寫作這本書的第一版的2017年，正是心理科學再現危機(Replication Crisis)，逐漸轉變為心理科學可信度危機(Credibility Crisis)的時候 [@vazireImplicationsCredibilityRevolution2018; @nosekReplicabilityRobustnessReproducibility2022]。

2011年是歐美心理學界深刻感受粗糙的研究方法長期損害心理科學品質的關鍵時間。當年有曾於「科學」(Science)發表研究的荷蘭社會與人格心理學者Diederik Stapel被揭發研究造假[@stapelFakingScienceTrue2014]，以及美國資深社會與人格心理學者Daryl Bem發表結論有爭議且結果難以重現的超感知覺研究[@bemFeelingFutureExperimental2011]。後續緊接發生的類以案例，啟發一群心理學者提出改進心理科學研究流程的主張[@chambers_trust_2013; @lindsayResearchPreregistration1012016]，並付諸於大規模再現研究[@camererEvaluatingReplicabilitySocial2018; @kleinInvestigatingVariationReplicability2014; @opensciencecollaborationEstimatingReproducibilityPsychological2015]。各種再現研究的結果顯示令人難以接受的事實：2015年之前發表於頂尖期刊的多數心理學研究，經過嚴謹設計的再現研究與資料分析，能重現原始發現的比例未達一半。對於正在學學習的學生來說，**今天聽到教授講述某個有啟發性的研究，明天得知這項研究證據經不起考驗**，這樣的狀況不再是只會從一些實驗室聽到的傳說故事，而是在任何大學學習場域隨時都會發生的情節。

所謂「危機也是轉機」，在可信度危機時代開始接觸心理學的學生，更有機會發覺清楚的學習方向，這本教科書正是為了幫助學生認識如何設計有品質的心理學實驗，也能啟發獨立評估心理科學研究品質的多元能力。在這次的改版，我們定義「研究品質」能反應在研究結果的**證據強度**。如何評估心理學實驗的證據強度，還有設計達到預期證據強度的實驗研究，不是能一蹴可及的目標，這本書提供一個明確學習起點：**看到讓你想認識的研究結果，你會不會先去找看看研究者有沒有公開資料與預先註冊研究計畫？** -- 這也是這本書自我定位「開放科學取向」的基本理由。

::: {.callout-note title="簡介'證據強度'" collapse="true"}
簡單的解釋是用來顯示一份測試兩種預測結果相異的實驗模型的實驗研究，兩種模型預測成功程度的綜合指標。在各種實證科學領域，各式證據強度指標陸續產生，科學研究社群尚在觀察如何運用證據強度指標。
:::

<!---
### 本書的設計理念

建立學習情境才能保持學習者對重要課題的興趣與專注，基於相關學習理論及建議操作[@Lave-1991; @chapmanUpgradeYourCargo2016]，本書提供教師與學生經營學習開放科學操作的輔助原則及建議。第一單元不只介紹有經驗的心理科學研究者熟悉的知識循環，也討論未實踐科學誠信所帶來的長期不良影響。科學誠信在本書指向能提出經得起細節檢驗的研究操作，所以本書不像其他心理學實驗法教材 一樣，鉅細靡遺地解說或討論好幾件研究課題的操作細節，而是提供教師及學生參考資源，營造能規劃並執行完整再現專案的學習情境。在此情境中完成一件再現專案，學生將完整體驗如何運用預先註冊(preregistration)建構個人的知識品質判斷準則，教師也能從每次過程中檢視自己所信守的理論，與在真實世界實踐的差異。--->

### 如何使用這本書

這本書不只是一本實驗心理學教科書，更是一本倡導開放科學理念、引導學生進行嚴謹科學研究的入門書。透過學習書中的內容和方法，學生可以掌握設計和執行高品質心理學實驗的技巧，培養鑑別心理學實驗品質的眼光。提供給使用本書學習的學生一些建議：

* **將本書視為學習如何設計高品質心理學實驗的起點**：
  * 根據「科學方法」設計的學習架構，學習如何收集、整理和閱讀心理學論文，透過學習過程內化「科學方法」為個人的思考方法。
  * 認識「證據強度」的可用指標，運用指標設計具備預期證據強度的實驗方法。

* **培養批判性思考，理性質疑既有的研究結果**：
  * 本書提供通俗及經典的研究案例，說明即使是廣泛流行的理論，也可能缺乏經得起考驗的科學證據支持，讀者可由這些案例學習以批判角度審視各種基於科學研究的主張和觀念。
  * 本書提供示範研究者如何公開研究資料以及預先註冊研究計畫，可從示範中學習獨立評估心理科學研究品質。

* **以經典實驗範例作為研究靈感，設計自己的研究**:
  * 本書介紹的重製研究涵蓋記憶研究、心理計時學研究和語言研究等多個領域的經典實驗，詳細說明這些實驗的理論背景、實驗設計和重要結果。
  * 讀者可以比較原始實驗與 @Zwaan-2018 重製實驗的設計差異、使用開源實驗平台重現實驗結果，並思考如何將這些實驗改進或應用到其他研究問題上。


* **善用本書介紹的學習資源**:
  * 以 @Chandler-2015 與 @Zwaan-2018 的重製研究專案為主軸，講解如何進行文獻回顧、設定研究問題和假設、設計實驗、分析資料和撰寫報告。
  * 本書提供開源實驗設計平台、統計分析方法、如何使用書目管理軟體、如何撰寫預先註冊研究計畫等可免費使用的資源。不僅能幫助讀者學習科學方法，也能適用到任何領域的知識管理。

<!--- 

version 1 backup

-   寫作動機

心理學實驗法是帶領心理學學生了解如何準備及完成一項心理學實驗的課程，也是研究操作養成入門。有百年歷史的心理學系都將這門課程設為必修課，許多有心深入心理學知識殿堂的學生從這門課程找到起點。寫出一本實驗心理學教科書也是一名心理學教師的生涯里程碑，但是我寫這本書的時機，正是心理科學重製危機(Replication Crisis)，逐漸轉變為心理科學品質危機(Quality Crisis)。 

2011年是歐美心理學界深刻感受粗糙的研究方法長期損害心理科學品質的關鍵一年。當年有曾於「科學」(Science)發表研究的荷蘭社會與人格心理學者Diederik Stapel被揭發研究造假[@stapelFakingScienceTrue2014]，以及美國資深社會與人格心理學者Daryl Bem發表結論有爭議且結果難以重現的超感知覺研究[@bemFeelingFutureExperimental2011]。後續緊接發生的類以案例，啟發一群心理學者提出改進心理科學研究流程的主張[@chambers_trust_2013; @lindsayResearchPreregistration1012016]，並付諸於大規模再現研究[@camererEvaluatingReplicabilitySocial2018;  @opensciencecollaborationEstimatingReproducibilityPsychological2015]。行動結果顯示令人難以接受的事實：近幾年發表於頂尖期刊的多數心理學研究，經過嚴謹的設計再現研究與分析，能重現原始發現的比例未達一半。對於正在學學習的學生來說，今天聽到教授講述某個有啟發性的研究，明天得知這項研究證據經不起考驗，這樣的狀況不再是想像，而是隨時可能會發生的日常情節。

如何讓心理學學生在品質危機時代，有個清楚的方向，是我編寫這本書的目的。首先是心理建設：今天起要學習實驗研究法的學生，正面臨放任心理科學每況愈下，或參與重建品質的抉擇機會。不論你會不會以心理學研究為終生事業，有能明辨心理科學研究品質的眼光，就能為重建心理科學品質貢獻一點力量。什麼樣的知識份子是一位有明辨心理科學研究品質的心理學人，這本書有個明確學習目標：**看到讓你想分享的研究結果，你會先去找研究者有沒有公開資料與註冊研究計畫？**

-   本書的設計理念

建立學習情境才能保持學習者對重要課題的專注，基於相關學習理論及建議操作[@laveSituatedLearningLegitimate1991; @chapmanUpgradeYourCargo2016]，本書提供教師與學生經營學習開放科學操作的輔助原則及建議。第一單元不只介紹有經驗的心理科學研究者熟悉的知識循環，也討論未實踐科學誠信所帶來的長期不良影響。科學誠信在本書指向能提出經得起細節檢驗的研究操作，所以本書不像其他心理學實驗法教材 一樣，鉅細靡遺地解說或討論好幾件研究課題的操作細節，而是提供教師及學生參考資源，營造能規劃並執行完整再現專案的學習情境。在此情境中完成一件再現專案，學生將完整體驗如何運用預先註冊(preregistration)建構個人的知識品質判斷準則，教師也能從每次過程中檢視自己所信守的理論，與在真實世界實踐的差異。

-   如何使用這本書

本書第二單元介紹心理科學領域的開放科學實踐者常用的工具，先展示出來是讓學生得知會在規劃及執行再現專案的過程，會運用的工具。我建議教師在配合第三到第六單元，設計讓學生學習使用各種工具的作業。第三到第六單元設計的內容，是個人熟知或有完整考資源的心理學研究課題，教師可根據個人專長，參考單元架構設計自己的課程內容。第七單元整理最新預先註冊案例及個人教研經驗，提供教師及學生規劃及執行自己的專案。

以電子書寫作能在每一次的改良過程，持續融合最新的資訊及有用指南。最初版電子書上線前，已經在OSF逐年更新教學大綱及參考資訊，現在彙整於公開的OSF專案( osf.io/a4ctm/ )。除了我自己的教學資料，也歡迎取用本書的教師運用OSF公開教學資料。本書附錄將逐年紀錄，見證心理學研究教學的改進過程。

--->

